### PR TITLE
Use CDN links for rawgit.

### PR DESCRIPTION
**Pull request by ryanpcmcquen**

### CODE REVIEW

**Comment by wernight** [comment]
Thanks. Could you:

- include why it's better in the description
- use `master` instead of the commit ID

Did you check it works on terminal extension?

**Comment by ryanpcmcquen** [comment]
It's working here on my Cloud9 workspace. You cannot use `master` because the CDN only caches once, meaning it would never update if `master` was used.

**Comment by ryanpcmcquen** [comment]
Would something like this work?

> Note that the RawGit links require a specific commit id, because files are cached permanently. Please update your projects to use the `CDN` links, as overusage of the development URLs (those without `cdn.`, could result in this repo being blacklisted from RawGit.

**Comment by wernight** [comment]
That description is good. Just for users this means a lot more work to keep it updated. I don't see this as being a good solution, but it's indeed better than throttle/blocking.

**Comment by ryanpcmcquen** [comment]
We could look into other CDNs that may be more _user_ friendly for future releases. :smiley_cat:

**Pull request merged**
