### PR TITLE
More fonts

### PR DESCRIPTION
**Pull request by tikiking1**
Adds all the powerline patched fonts.

### CODE REVIEW

**Comment by wernight** [comment]
Great work. Two things please:

 - Please squash into a single commit (if you don't know how to do that you can ask me)
 - For backward compatibility it should include `Source Code Pro for Powerline` which is also the name of the font when natively installed.

**Comment by tikiking1** [comment]
I think that should do it.

**Comment by wernight** [comment]
Nice now I can fully review it.

* Any reason you're not using [woff2 which should be 30-50% smaller](https://gist.github.com/sergejmueller/cf6b4f2133bcb3e2f64a) and it may matter as it is downloaded frequently (actually might have to change the download URL to a more CDNS friendly one at some point).
* Also I'd suggest to include a `local()` when you know the local name, so that for example people with Crouton or just using Linux/Windows can install them locally and they'd get used without further due.
* Rename `index.html` to `test.html` or similar name.

**Comment by tikiking1** [comment]
I'm doing the WOFF2 conversion and adding `local()` fonts now. As for the CDN and `index.html`, I'm intending to use GitHub Pages as the CDN.

**Comment by tikiking1** [comment]
Both are done; I'll rename `index.html` to `test.html` if you want, but I'd prefer to keep it as `index.html` because of GitHub Pages.

**Comment by tikiking1** [comment]
Cancel that; something got borked in the conversion (although it might just be my system). I'll take a look at it in the morning...

**Comment by wernight** [comment]
What do you mean by "because of GItHub Pages"? May be in as `tests/index.html`?

**Comment by tikiking1** [comment]
So [it validates as proper CSS now](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Ftikiking1.github.io%2Fpowerline-web-fonts%2FPowerlineFonts.css&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en) (should've checked that 6 hours ago...), but I think Fontforge misconverted the fonts or something, because it's still not working in Secure Shell...

I'm literally just doing
```
#!/usr/bin/env fontforge
Open($1)
Generate($1:r + ".woff2")
```

for the conversion because I can't find the script I had to do it originally; I'm reconverting the fonts to see if that'll fix them otherwise. Man, it's *annoying* to do font work on a Chromebook...

**Comment by tikiking1** [comment]
Okay, it seems to work now (at long last).

**Comment by wernight** [comment]
Looking good. Hate to be such a drag, just would you mind squashing them again. Looks like everything else it fine and thanks for your work. It's really cool!

**Comment by tikiking1** [comment]
Done!

**Pull request merged**
